blockchaintp/daml-on-sawtooth

BUILD.md
bin/build.sh

Correction to build.sh and instructions for local development

---

CODEOWNERS

Updates to CODEOWNERS
* Add Jussi Maki
* Add Marcin Ziolek
* Add Brian Healey

Oss scaffolding

---

sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/SawtoothWriteService.java

This pull 
* refactors party allocation, transaction submisssion, and archive upload to a more uniform pattern.
* corrects the party allocation to be a daml submission

Refactor submissions and correct party allocation

---

BUILD.md
README.md

Couple of minor markdown edits

---

tracer-ui/package.json
tracer-ui/yarn.lock

Fix to deal with nodeJS dependencies security violation reported by Github
Signed-off-by: Paul Sitoh <paulwizviz@gmail.com>

Update dependencies to version recommended

---

BUILD.md
README.md

wrapping up pr-44 and pr-45 to rebase together.

Documentation fixes

---

Jenkinsfile

ci: keep images after build

---

.pre-commit-config.yaml
docker/daml-test.yaml
sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/SawtoothLedgerWriter.java
sawtooth-daml-rpc/src/main/scala/com/blockchaintp/sawtooth/daml/rpc/Main.scala
timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/TimeKeeperTransactionProcessorMain.java
timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/processor/GlobalTimeState.java
timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/processor/ParticipantTimeState.java
timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/processor/TimeKeeperTransactionHandler.java
timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/processor/TimestampUtils.java

Corrections and hardnening of Timekeeper time calculation 

---

timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/TimeKeeperRunnable.java

feat(timekeeper): add exponential back off to timekeeper

---

docker/daml-test.yaml
sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/ZmqEventHandler.java
sawtooth-daml-tp/src/main/java/com/blockchaintp/sawtooth/daml/processor/ContextLedgerState.java

which is slowing down the integration test of the build

ci(docker): reduce logging of daml-tp

---

timekeeper/src/main/java/com/blockchaintp/sawtooth/timekeeper/TimeKeeperRunnable.java

fix(timekeeper): correct initial backoff counter increment

---

Jenkinsfile
Makefile
bin/semver
build-tools/pom.xml
daml-on-sawtooth-protobufs/pom.xml
pom.xml
sawtooth-daml-common/pom.xml
sawtooth-daml-rpc/pom.xml
sawtooth-daml-tp/pom.xml
timekeeper/pom.xml

Also add sonar analysis and report on unit tests

ci: convert to use Makefile based build

---

.dockerignore
.gitignore
sawtooth-daml-common/src/main/java/com/blockchaintp/utils/DirectoryKeyManager.java
sawtooth-daml-common/src/main/java/com/blockchaintp/utils/InMemoryKeyManager.java
sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/DamlAuthServices.java
sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/SawtoothLedgerWriter.java
sawtooth-daml-tp/pom.xml
sawtooth-daml-tp/src/test/java/com/blockchaintp/sawtooth/daml/processor/ContextLedgerStateTest.java

fix: correct issues arising from sonar checks

---

.gitignore
.pre-commit-config.yaml
BUILD.md
Jenkinsfile
Makefile
docker/docker-compose-build.yaml
docker/toolchain.docker
pom.xml
standard_defs.mk

* updates the build to the standard Makefile patterns
* add the repository reference for btp-releases
* update the build instructions

Build pattern and documentation update

---

sawtooth-daml-tp/src/main/java/com/blockchaintp/sawtooth/daml/processor/ContextLedgerState.java
sawtooth-daml-tp/src/main/java/com/blockchaintp/sawtooth/daml/processor/DamlTransactionHandler.java

Unfortunately sl4j does not support lambdas, except in v2-alpha which
has had no other versions since 2019
Signed-off-by: Ryan Roberts <ryan@blockchaintp.com>

Guard expensive log operations

---

sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/AuthorizationHeaderMissing.java
sawtooth-daml-rpc/src/main/java/com/blockchaintp/sawtooth/daml/rpc/DamlAuthServices.java

This style is cheap in sum type languages, and can probably be
reproduced
Signed-off-by: Ryan Roberts <ryan@blockchaintp.com>

A very much more specific exception

---

.gitignore
.readthedocs.yaml
docs/index.md
mkdocs.yml

docs: add mkdocs setup

---

pom.xml

build(deps): update paralos-java and slf4j deps

---

.github/CODEOWNERS
.github/settings.yml
CODEOWNERS
Makefile

ci(make): correct docker logs extraction

---

pom.xml
sawtooth-daml-rpc/pom.xml

supersedes #119 addressing FOSSA issue

bump dependencies for google guava and reactive streams
